### ISSUE TITLE
Error when clicking on canvas

### ISSUE THREAD

**Issue by pcav** [enricofer/redLayer#1]
Traceback (most recent call last):
  File "/home/paolo/.qgis2/python/plugins/redLayer/redLayerModule.py", line 355, in canvasReleaseEvent
    self.gestures += 1
AttributeError: 'redLayer' object has no attribute 'gestures'

**Comment by csandor** [comment]
I think this could be the same issue:
Traceback (most recent call last):
  File "C:/Users/sando_000/.qgis2/python/plugins\redLayer\redLayerModule.py", line 457, in canvasReleaseEvent
self.geoSketches.append([self.currentColor.name(),str(self.currentWidth),self.sketch,None,"",self.gestures])
AttributeError: 'redLayer' object has no attribute 'gestures'

QGIS 2.10 (win10)

**Comment by enricofer** [comment]
Could you help me to replicate the issue providing dataset and operating steps that bring to exception?

**Comment by pcav** [comment]
I just load a polygon layer and start drawing, then I get the exception:

AttributeError: 'redLayer' object has no attribute 'gestures' 
Traceback (most recent call last):
  File "/home/paolo/.qgis2/python/plugins/redLayer/redLayerModule.py", line 402, in canvasMoveEvent
    self.geoSketches.append([self.currentColor.name(),str(self.currentWidth),sketch,None,"",self.gestures])
AttributeError: 'redLayer' object has no attribute 'gestures'

**Comment by csandor** [comment]
Same here. I submitted a pull request with the only change to initialize the gestures property with 0 in the beginning. This solved the issue for me.

**Comment by enricofer** [comment]
Nothing. In my linux and windows systems everything goes as expected. Using mouse....
self.gestures is a variable that is defined at canvasPressEvent. 
It appears that you are moving cursor without having pressed it on screen.....
I thing that predefining the variable during plugin installation should resolv. To do this simply edit redLayerModule.py file and put at the end of initGui function after row 229 the following row:
`self.gestures = 0`
I suppose the interaction with canvas in your sistems does not go as expected (using pencil?)

**Comment by enricofer** [comment]
I see now the reply of Sandor! Great! It goes. Thank you for PR.

**Comment by csandor** [comment]
I use it on the desktop with mouse not touchscreen. :)
