### ISSUE TITLE
Toolbar not enabled

### ISSUE THREAD

**Issue by boesiii** [enricofer/redLayer#10]
I have just installed the latest version of your plugin.  I am not able to enable the toolbar buttons, they always stay grey.  I have created new projects and saved the projects but still the tools are always disabled.

How can I enable the tools?

**Comment by boesiii** [comment]
i am using Qgis 3.4.11

**Comment by enricofer** [comment]
I can't replicate issue.
Did you save and reopen new or current project?
At the first install the plugin does not connect to the current project until it is saved.
Try to restart QGIS and let me know if you solved.

**Comment by boesiii** [comment]
I did save and reopen multiple times yesterday but I still got nothing.  I just tried again and it is working.  I don't know?
