### ISSUE TITLE
Error on first project opened with new QGIS session

### ISSUE THREAD

**Issue by jctull** [enricofer/redLayer#2]
If I open QGIS, then load a project file, this error is thrown for every layer being loaded in the project file (I think... it is thrown up a lot, assuming every layer). I'm on OS X (Mac) QGIS trunk.

An error has occured while executing Python code:

Traceback (most recent call last):
  File "/Users/jctull/.qgis2/python/plugins/redLayer/redLayerModule.py", line 368, in notSavedProjectAction
    QgsMapLayerRegistry.instance().legendLayersAdded.disconnect(self.notSavedProjectAction)
TypeError: disconnect() failed between 'legendLayersAdded' and 'unislot'

Python version:
2.7.9 (default, Feb 10 2015, 03:28:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]

QGIS version:
2.9.0-Master Master, aaabad2

Python path: ['/Users/jctull/.qgis2/python/plugins/sextante_animove', '/Users/jctull/.qgis2/python/plugins/QSDM', '/Users/jctull/.qgis2/python/plugins/processinglwgeomprovider', '/Users/jctull/.qgis2/python/plugins/processing', '/Users/jctull/.qgis2/python/plugins/postgis_geoprocessing', '/usr/local/Cellar/qgis-28/HEAD/QGIS.app/Contents/MacOS/../Resources/python', u'/Users/jctull/.qgis2/python', u'/Users/jctull/.qgis2/python/plugins', '/usr/local/Cellar/qgis-28/HEAD/QGIS.app/Contents/MacOS/../Resources/python/plugins', '/usr/local/lib/python2.7/site-packages/python_itunes-1.0-py2.7.egg', '/usr/local/Cellar/qgis-28/HEAD/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages', '/', '/usr/local/lib/python2.7/site-packages/gst-0.10', '/usr/local/lib/python2.7/site-packages/gtk-2.0', '/usr/local/lib/python2.7/site-packages/wx-3.0-osx_cocoa', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/usr/local/Cellar/matplotlib/1.4.3/libexec/lib/python2.7/site-packages', '/usr/local/Cellar/numpy/1.9.2/libexec/nose/lib/python2.7/site-packages', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gst-0.10', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gtk-2.0', '/Library/Python/2.7/site-packages', u'/Users/jctull/.qgis2//python', '/Users/jctull/.qgis2/python/plugins/DigitizingTools/tools', '/Users/jctull/.qgis2/python/plugins/irods_qgis', '/Users/jctull/.qgis2/python/plugins/mmqgis/forms', '.', '/Users/jctull/.qgis2/python/plugins/SelectTools/tools', '/usr/local/Cellar/qgis-28/HEAD/QGIS.app/Contents/Resources/python/plugins/fTools/tools']

**Comment by enricofer** [comment]
The issue happened to me too. But now I'm not anymore able to replicate issue. Can you help me submitting sample data and step by step instructions to get the error?

**Comment by Jorishin** [comment]
![beforeclosingerrormsgs](https://cloud.githubusercontent.com/assets/12510749/7700439/0087d8be-fe1f-11e4-930e-d637bcdbab69.png)
![afterclosingerrormsgs](https://cloud.githubusercontent.com/assets/12510749/7700441/01fc1caa-fe1f-11e4-9e3f-33b77609b243.png)

Same here, working on OS X 10.10.3, QGIS 2.8.1.
When the  RedLayer plugin is activated, when loading a project, for each layer I Get the error message. After Closing the error message, a layer in the layer pane gets its styling properties.

**Comment by enricofer** [comment]
fixed and updated on repository
https://github.com/enricofer/redLayer/commit/eee5f4985284f6a5473de480637cca5b8d0ed376

**Comment by jctull** [comment]
My apologies for not getting back to the earlier request. I will try the updated plugin shortly and report back.

**Comment by jctull** [comment]
Things are working well after a reinstall and restart of QGIS. Thank you for this excellent tool!

**Comment by Jorishin** [comment]
OK, error messages do no longer appear. Great work!
Joris
