### ISSUE TITLE
Is a release planned with latest fixes and improvments?

### ISSUE THREAD

**Issue by Guts** [enricofer/redLayer#22]
Hello @enricofer ,

Do you plan to release a new version to plugins.qgis.org in next days?
I need to know for my end-users.

thanks!

**Comment by enricofer** [comment]
If you you are not submitting any other commit I can go with the new
release. Thanks

Il ven 26 feb 2021, 14:37 Julien <notifications@github.com> ha scritto:

**Comment by Guts** [comment]
I'm not. I've got a feedback from a Linux user and from a Windows one: everything seems to work like a charm :).

Thanks!

**Comment by enricofer** [comment]
I submitted the plugin and it will soon be published. Thanks for your contribution.

**Comment by enricofer** [comment]
Plugin Red Layer approval by zimbogisgeek.
The plugin version "[752] Red Layer 2.1" is now approved
Link: http://plugins.qgis.org/plugins/redLayer/
