### ISSUE TITLE
Unable to save sketch with QGIS LTR 3.16

### ISSUE THREAD

**Issue by esnyder-rve** [enricofer/redLayer#23]
I love this plugin, but this commit: 8356ecf9642f7cd9c72a69a529619633487aef79 breaks the plugin.
```python
# Line 676 of redLayerModule.py:
with out_sketch_path.open(mode="w", encoding="UTF8") as f:
#    ^ This is a string, not a file handle
```
I get the error message `'str' object has no attribute 'open'`

**Comment by enricofer** [comment]
fixed https://github.com/enricofer/redLayer/commit/8bbd5eddf6ab525797700d80d8832ce010ecfde5
I will submit it to QGIS plugins repo soon

**Comment by enricofer** [comment]
memo for @Guts

**Comment by Guts** [comment]
Thanks @enricofer for the quick fix. IMHO it would be better to switch right now from old `os.path` to modern `pathlib`. It's much better and robust against different file and operating systems.
