### ISSUE TITLE
Could not load plugin...

### ISSUE THREAD

**Issue by chau-intl** [enricofer/redLayer#3]
Hi!

I've got the following error message on startup. I have removed and reinstalled the plugin, but it doesn't help.

Couldn't load plugin redLayer due to an error when calling its initGui() method

Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 231, in startPlugin
    plugins[packageName].initGui()
  File "C:/Users/..../.qgis2/python/plugins\redLayer\redLayerModule.py", line 221, in initGui
    self.gestures = 0
AttributeError: 'redLayer' object has no attribute 'self'

Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

QGIS version:
2.11.0-Master Master, 6a6adc9

**Comment by enricofer** [comment]
Thank for submission.
Does the issue appear with qgis master?

**Comment by chau-intl** [comment]
> QGIS version:
> 2.11.0-Master Master, 6a6adc9

YES, but what I don't know is if the issue actually exist in 2.10.1.

**Comment by chau-intl** [comment]
I have just tried deleting the redlayer folder under python/plugins and installing the plugin afterwards, and it seems to remove the issue. So something is not properly cleaned up by doing an uninstall of the plugin.

Feel free to close the issue if you think the problem lies outside of your plugin scope.

**Comment by enricofer** [comment]
No exception in my testing systems.
I left the issue opened waiting for further feedback.
Thanks.

2015-10-22 12:34 GMT+02:00 Casper notifications@github.com:
