### ISSUE TITLE
Point with Annotation

### ISSUE THREAD

**Issue by gis-haderslev** [enricofer/redLayer#4]
Thanks for useful plug-in. I miss option to add an Annotation(existing bubble annotation) out of drawing a line. Just on click, like point with bubble annotation, when Annotation is chosen.

**Comment by enricofer** [comment]
Annotations is a core feature accesible from standard qgis menu with an icon like this: ![annotation](http://docs.qgis.org/1.8/en/_images/mActionTextAnnotation.png). The usage is like you described: Point on screen and write. You can also more annotate with html or an image...
Redlayer make use of annotation feature to assign e textual note to a sketch.
I hope I understood what you mean.
Regards

**Comment by gis-haderslev** [comment]
Thanks a lot. Regards.
