### ISSUE TITLE
Add "Undo" (Ctrl-Z) (enhancement request)

### ISSUE THREAD

**Issue by sfkeller** [enricofer/redLayer#41]
Hi Enrico

Very nice pluign which probably will be more and more in demand in many domains. 
I have an enhancement request: 
Can you add "Undo" (Ctrl-Z)?

Yours, Stefan

**Comment by enricofer** [comment]
Hi, at the moment I have no plans to put hands on current code.
But Maybe some enhancements could be introduced when the plugin will need to be migrated to Qt6.

**Comment by sfkeller** [comment]
Ciao Enrico: Thanks for you quick answer. You wrote:
> at the moment I have no plans to put hands on current code.

Ok. But are you acceping pull requests (i.e. from us / Geometa Lab)?

> But Maybe some enhancements could be introduced when the plugin will need to be migrated to Qt6.

Well, that's an issue for the future (and no plans AFAIK from the [QGIS project](https://github.com/qgis/QGIS-Enhancement-Proposals/issues/243)). 
What users - and we - need, are enhancements for the current QGIS / PyQt5 😃  .

**Comment by enricofer** [comment]
Yes. feel free to contribute.
