### ISSUE TITLE
Red Layer deletes text annotations from project

### ISSUE THREAD

**Issue by spaceof7** [enricofer/redLayer#7]
I am using Red Layer in QGIS 2.14.7 OSGEO4W64.  The first problem I had was when some users recently upgraded from 2.8 LTR to 2.14 LTR no text annotations would show although they were in the .qgs file. Saving the project will delete them.  As I tested I noticed that if I add non-Red Layer annotations, the next time i open the project the annotations get deleted.  If I disable Red Layer plugin this doesnt happen.

**Comment by enricofer** [comment]
Thanks for issue submission.
I applied a fix to loading function. https://github.com/enricofer/redLayer/commit/ebc932aec945eb534863311f9d78f39dd175afe0 
Could you test it?

**Comment by spaceof7** [comment]
I just tested it but unfortunately I'm getting the same behaviour.

**Comment by enricofer** [comment]
I tested the plugin and I didn't found the reported issue, unless annotations (redlayer and non redlayer) have the same content ....
Annotations in QGis are stored in a quite different way from map features. They have not e featureid, and a comprehensive API interface. So rethrieving them from plugin once they are created is impossible.
The plugin intercept them in xml file before saving project and if the a note content is corresponding to one of those defined by plugin is recognized as redlayer note and is expunged delegating notes loading to plugin procedure. (have a look to redLayerModule.py from row 546 to 562 in beforeSaveProjectAction function)
So if a conventional note has the same content of a red layer note is erased saving Project without being handled by the plugin itself (rows 559-561).
At the moment I have no idea on solving this issue so the only solution is to make non red layer notes different from red-layer notes with a text prefis/suffix Uppercase and so on...
I hope this helps you.

**Comment by spaceof7** [comment]
Thanks for the explanation, I appreciate it, and my apologies if i am just not understanding something, but I think there is a case where Red Layer deletes annotations that you missed that may or may not be fixable.  This happens on loading the project, not saving.  It looks like  projectReadAction is calling removeSketchesAction which in turn calls removeAllAnnotations.  I did some testing and if I comment-out line 363(the call to removeAllAnnotations) my annotations do not disappear when loading a project, but I have no idea what other problems might be caused by commenting this out.  Is there a way to avoid clearing the annotations on loading a project?

**Comment by enricofer** [comment]
Could you provide datasets and operating steps to reproduce issue locally?

**Comment by spaceof7** [comment]
Sure, I've attached a project file and shapefile.  There are no RedLayer sketches associated with the project(I tested with and without a sketch file).  To reproduce:
1. Open the project in 2.14.7 or 2.16.3(I think I also tested with master) with RedLayer enabled. No annotations are displayed. 
2. Disable RedLayer and close QGIS.  Do not save project changes.
3. reopen the project.  Now annotations will be displayed.

alternately to reproduce:
start a new project.
add a text annotation.
save the project.
close qgis.
start qgis and open the project.  The annotation(s) do not show on opening.

Oh, also, when testing I disabled all plugins except RedLayer.

[annot_test.zip](https://github.com/enricofer/redLayer/files/543160/annot_test.zip)

**Comment by enricofer** [comment]
The reported issue is finally fixed: https://github.com/enricofer/redLayer/commit/b20788b957859b3ba2a6f6aadcffc019d653bbfe
Download it from master
Please help me to check  other unexpected issues related to the fix.
Thanks for submission

**Comment by spaceof7** [comment]
Fabulous!  I tested it out today and didn't find any problems.  I'll continue testing and let you know if I notice anything.  Thanks for your work!
