### ISSUE TITLE
Error on load Plugin

### ISSUE THREAD

**Issue by Shuffle20** [enricofer/redLayer#9]
Hi, I have an error message on load the plugin
QGIS 3.8.2-Zanzibar / Windows 10 Pro 64 bit v.1903

Impossibile caricare il plugin 'redLayer' a causa di un errore chiamando il metodo classFactory() 
ModuleNotFoundError: No module named 'resources_rc' 

![error](https://user-images.githubusercontent.com/55176570/64672111-d6fc6d80-d46a-11e9-8b8f-3da5ffc7c0f4.jpg)

**Comment by enricofer** [comment]
Line 31 in redLayerModule.py is no longer needed. Simply remove it to solve the issue. 
I will soon update the repository.
Thanks for submission.

**Comment by Shuffle20** [comment]
Solved!
Thank you very much

**Comment by enricofer** [comment]
fixed https://github.com/enricofer/redLayer/commit/b7b1d45585c87d9c73bde90454a18cfb919cb588
